/**
 * cueSheetExporter — Generate CD-standard cue sheets for album delivery
 *
 * A cue sheet (.cue) is the industry standard for specifying track layout
 * on a CD or DDP image. Required for physical CD manufacturing, mastering
 * delivery to distributors (DistroKid Pro, CD Baby Pro, label portals),
 * and DDP image creation.
 *
 * Formats:
 *   1. Standard CUE sheet (single-file or multi-file)
 *   2. DDP-compatible CUE (ISRC, catalog, UPC)
 *   3. CSV track listing (for label delivery metadata)
 *   4. XML (iTunes/Apple Music album delivery format)
 *
 * Timing: CUE sheets use MM:SS:FF (frames) where 1 frame = 1/75 second.
 * Gap between tracks: standard 2-second pregap per Red Book standard.
 */

export interface CueTrack {
  index:       number;          // 1-based track number
  title:       string;
  artist?:     string;
  isrc?:       string;          // ISRC code: CC-XXX-YY-NNNNN
  startSec:    number;          // start time in seconds (cumulative)
  durationSec: number;          // track duration in seconds
  pregapSec?:  number;          // pregap before this track (default 2.0 for track 2+)
  lufs?:       number;          // measured integrated LUFS
  truePeak?:   number;          // dBTP
}

export interface CueSheetOptions {
  albumTitle:   string;
  albumArtist:  string;
  catalog?:     string;         // UPC/EAN barcode
  discId?:      string;         // MusicBrainz disc ID
  label?:       string;
  year?:        string;
  genre?:       string;
  filename?:    string;         // WAV/FLAC filename (for single-file cue)
  multiFile?:   boolean;        // true = one FILE per track
  tracks:       CueTrack[];
}

// ── Format helpers ────────────────────────────────────────────────────────────

function secToMsf(sec: number): string {
  const totalFrames = Math.round(sec * 75); // 75 frames/sec (Red Book)
  const frames = totalFrames % 75;
  const totalSecs = Math.floor(totalFrames / 75);
  const secs = totalSecs % 60;
  const mins = Math.floor(totalSecs / 60);
  return `${String(mins).padStart(2, '0')}:${String(secs).padStart(2, '0')}:${String(frames).padStart(2, '0')}`;
}

function validateIsrc(isrc: string): boolean {
  // ISRC format: CC-XXX-YY-NNNNN (12 chars without hyphens)
  const clean = isrc.replace(/-/g, '');
  return /^[A-Z]{2}[A-Z0-9]{3}\d{7}$/.test(clean);
}

// ── CUE sheet ────────────────────────────────────────────────────────────────

export function generateCueSheet(opts: CueSheetOptions): string {
  const lines: string[] = [];

  // Header
  lines.push(`REM GENRE ${opts.genre ?? 'Pop'}`);
  lines.push(`REM DATE ${opts.year ?? new Date().getFullYear()}`);
  if (opts.catalog)  lines.push(`CATALOG ${opts.catalog}`);
  if (opts.discId)   lines.push(`REM DISCID ${opts.discId}`);
  if (opts.label)    lines.push(`REM LABEL ${opts.label}`);
  lines.push(`REM COMMENT "Generated by Echo Sound Lab 2.5"`);
  lines.push(`PERFORMER "${opts.albumArtist}"`);
  lines.push(`TITLE "${opts.albumTitle}"`);

  if (!opts.multiFile) {
    const fname = opts.filename ?? `${opts.albumTitle.replace(/[^a-zA-Z0-9 ]/g, '_')}.wav`;
    lines.push(`FILE "${fname}" WAVE`);
  }

  let cursor = 0; // running time position in seconds
  for (const track of opts.tracks) {
    if (opts.multiFile) {
      const fname = `${String(track.index).padStart(2, '0')}_${track.title.replace(/[^a-zA-Z0-9 ]/g, '_')}.wav`;
      lines.push(`FILE "${fname}" WAVE`);
    }

    lines.push(`  TRACK ${String(track.index).padStart(2, '0')} AUDIO`);
    lines.push(`    TITLE "${track.title}"`);
    lines.push(`    PERFORMER "${track.artist ?? opts.albumArtist}"`);

    if (track.isrc && validateIsrc(track.isrc)) {
      lines.push(`    ISRC ${track.isrc.replace(/-/g, '')}`);
    }

    // Pregap (index 00) — 2 seconds for tracks 2+ per Red Book
    const pregap = track.pregapSec ?? (track.index > 1 ? 2.0 : 0);
    if (pregap > 0) {
      lines.push(`    INDEX 00 ${secToMsf(cursor)}`);
      cursor += pregap;
    }

    lines.push(`    INDEX 01 ${secToMsf(cursor)}`);

    // Loudness metadata as comments
    if (track.lufs    != null) lines.push(`    REM LUFS ${track.lufs.toFixed(1)}`);
    if (track.truePeak != null) lines.push(`    REM TRUEPEAK ${track.truePeak.toFixed(1)}`);

    cursor += track.durationSec;
  }

  return lines.join('\n') + '\n';
}

// ── CSV track listing ─────────────────────────────────────────────────────────

export function generateTrackListCsv(opts: CueSheetOptions): string {
  const header = 'Track,Title,Artist,ISRC,Duration,Start,LUFS,TruePeak';
  const rows = opts.tracks.map(t => {
    const dur = formatDuration(t.durationSec);
    const start = formatDuration(t.startSec);
    return `${t.index},"${t.title}","${t.artist ?? opts.albumArtist}","${t.isrc ?? ''}",${dur},${start},${t.lufs?.toFixed(1) ?? ''},${t.truePeak?.toFixed(1) ?? ''}`;
  });
  return [header, ...rows].join('\n') + '\n';
}

function formatDuration(sec: number): string {
  const m = Math.floor(sec / 60);
  const s = Math.floor(sec % 60);
  const ms = Math.round((sec % 1) * 1000);
  return `${String(m).padStart(2, '0')}:${String(s).padStart(2, '0')}.${String(ms).padStart(3, '0')}`;
}

// ── XML (iTunes LP / Apple Music delivery) ────────────────────────────────────

export function generateAppleMusicXml(opts: CueSheetOptions): string {
  const escXml = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
  const tracks = opts.tracks.map(t => `
    <track>
      <trackNumber>${t.index}</trackNumber>
      <title>${escXml(t.title)}</title>
      <artist>${escXml(t.artist ?? opts.albumArtist)}</artist>
      ${t.isrc ? `<isrc>${escXml(t.isrc)}</isrc>` : ''}
      <durationMs>${Math.round(t.durationSec * 1000)}</durationMs>
      ${t.lufs     != null ? `<integratedLoudness>${t.lufs.toFixed(1)}</integratedLoudness>` : ''}
      ${t.truePeak != null ? `<truePeak>${t.truePeak.toFixed(1)}</truePeak>` : ''}
    </track>`).join('');

  return `<?xml version="1.0" encoding="UTF-8"?>
<album>
  <title>${escXml(opts.albumTitle)}</title>
  <artist>${escXml(opts.albumArtist)}</artist>
  ${opts.catalog ? `<upc>${escXml(opts.catalog)}</upc>` : ''}
  ${opts.year    ? `<releaseYear>${escXml(opts.year)}</releaseYear>` : ''}
  ${opts.genre   ? `<genre>${escXml(opts.genre)}</genre>` : ''}
  ${opts.label   ? `<label>${escXml(opts.label)}</label>` : ''}
  <generatedBy>Echo Sound Lab 2.5</generatedBy>
  <tracks>${tracks}
  </tracks>
</album>\n`;
}

// ── Download helpers ──────────────────────────────────────────────────────────

export function downloadText(content: string, filename: string, mime = 'text/plain') {
  const blob = new Blob([content], { type: mime });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a'); a.href = url; a.download = filename; a.click();
  URL.revokeObjectURL(url);
}
